// Generated by sync.sh from the sketches/ folder. Do NOT TOUCH.
const SKETCHES = [
  { file: "banneroriginal.svg", width: 935, height: 244 },
  { file: "first_sketch.jpg", width: 1080, height: 1279 },
  { file: "icon.png", width: 118, height: 118 },
  { file: "not_sketch.jpg", width: 720, height: 1280 },
  { file: "penguin_adelie.png", width: 1080, height: 1080 },
];
