#!/bin/bash

# 1. Refresh the list of images the sketches gallery shows
{
  echo "// Generated by sync.sh from the sketches/ folder. Don't edit by hand."
  echo "const SKETCHES = ["
  find sketches -maxdepth 1 -type f -iregex '.*\.\(png\|jpe?g\|gif\|webp\|avif\|svg\)' -printf '%f\n' \
    | sort | sed 's/[\\"]/\\&/g; s/.*/  "&",/'
  echo "];"
} > sketches.js

# 2. Add all changes (HTML, CSS, PDF, etc.)
git add .

# 3. Create a commit with the current date and time
msg="Update: $(date +'%Y-%m-%d %H:%M:%S')"
git commit -m "$msg"

# 4. Push to GitHub
git push origin main

echo "✅ Main Hub updated successfully!"
