#!/bin/bash

# refresh the list of images the doodles gallery shows with their sizes
{
  echo "// Generated by sync.sh from the doodles/ folder. Do NOT TOUCH."
  echo "const DOODLES = ["
  find doodles -maxdepth 1 -type f -iregex '.*\.\(png\|jpe?g\|gif\|webp\|avif\|svg\)' -printf '%f\n' | sort |
    while IFS= read -r file; do
      read -r width height orientation < <(identify -ping -format '%w %h %[orientation]\n' "doodles/$file[0]" 2>/dev/null)
      case "$orientation" in LeftTop|RightTop|RightBottom|LeftBottom) read -r width height <<< "$height $width" ;; esac
      name=$(printf '%s' "$file" | sed 's/[\\"]/\\&/g')
      echo "  { file: \"$name\", width: ${width:-null}, height: ${height:-null} },"
    done
  echo "];"
} > doodles.js

git add .

msg="Update: $(date +'%Y-%m-%d %H:%M:%S')"
git commit -m "$msg"

git push origin main

echo "✅ Main Hub updated successfully!"
